pub mod bindings;
pub mod wrapper;

/// Simple namespace to redefine some autogenerated names
pub mod item_res {
    use crate::ffi::bindings::{
        Item_result, Item_result_DECIMAL_RESULT, Item_result_INT_RESULT, Item_result_REAL_RESULT,
        Item_result_STRING_RESULT,
    };

    pub const STRING_RESULT: Item_result = Item_result_STRING_RESULT;
    pub const REAL_RESULT: Item_result = Item_result_REAL_RESULT;
    pub const INT_RESULT: Item_result = Item_result_INT_RESULT;
    pub const DECIMAL_RESULT: Item_result = Item_result_DECIMAL_RESULT;
}
